#!/usr/bin/env bash
# Parses libpftrace's output with a protobuf runtime generated by protoc from
# tools/perfetto_min.proto. Run inside a nix-shell that provides protoc and
# python3 with the protobuf module; tools/run_checks.sh arranges that.
#
# Separate from run_checks.sh because it executes inside that nix-shell, and
# inlining a multi-line python heredoc through --run quotes badly.
set -euo pipefail

root=${1:?usage: check_schema.sh <root> <build-dir>}
build=${2:?usage: check_schema.sh <root> <build-dir>}
gen=$(mktemp -d)
trap 'rm -rf "$gen"' EXIT

protoc --proto_path="$root/tools" --python_out="$gen" \
    "$root/tools/perfetto_min.proto"

cd "$root/$build"
for f in demo_continuous demo_snapshot stress_paced stress_continuous; do
    [ -f "$f.pftrace" ] || continue
    echo "--- $f"
    PYTHONPATH="$gen" TRACE="$f.pftrace" python3 "$root/tools/check_schema.py"
done
